# Generated by Django 2.1.1 on 2018-10-01 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import asap.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(help_text='반드시 자신의 학교 이메일을 기입해야만 합니다.', max_length=254, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=1)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False, verbose_name='student status')),
                ('is_prof', models.BooleanField(default=False, verbose_name='teacher status')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', asap.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_number', models.CharField(max_length=6)),
                ('title', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('research_type', models.CharField(choices=[('T', '이론'), ('L', '실습')], max_length=1)),
                ('semester', models.CharField(choices=[('1', 'Spring'), ('2', 'Fall')], max_length=1)),
                ('max_number', models.PositiveIntegerField(default=0)),
                ('current_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.PositiveIntegerField(blank=True, null=True)),
                ('hw1', models.PositiveIntegerField(blank=True, null=True)),
                ('hw2', models.PositiveIntegerField(blank=True, null=True)),
                ('exam1', models.PositiveIntegerField(blank=True, null=True)),
                ('exam2', models.PositiveIntegerField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(blank=True, null=True)),
                ('score', models.CharField(blank=True, choices=[('A+', 'A+'), ('A0', 'A0'), ('B+', 'B+'), ('B0', 'B0'), ('C+', 'C+'), ('C0', 'C0'), ('D+', 'D+'), ('D0', 'D0'), ('F', 'F')], max_length=2, null=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asap.Research')),
            ],
        ),
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('prof_number', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_number', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='record',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asap.Student'),
        ),
        migrations.AddField(
            model_name='research',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asap.Prof'),
        ),
    ]