# Generated by Django 2.1.1 on 2018-11-19 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='attendence',
        ),
        migrations.RemoveField(
            model_name='record',
            name='exam1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='exam2',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hw1',
        ),
        migrations.RemoveField(
            model_name='record',
            name='hw2',
        ),
        migrations.RemoveField(
            model_name='research',
            name='research_type',
        ),
        migrations.AddField(
            model_name='research',
            name='hour',
            field=models.CharField(choices=[('00:00:00', '0시간'), ('01:00:00', '1시간'), ('02:00:00', '2시간'), ('03:00:00', '3시간'), ('04:00:00', '4시간'), ('05:00:00', '5시간')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='minute',
            field=models.CharField(choices=[('00:00:00', '0분'), ('00:15:00', '15분'), ('00:30:00', '30분'), ('00:45:00', '45분')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='place',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='start_time',
            field=models.CharField(choices=[('09:00:00', '09 AM'), ('10:00:00', '10 AM'), ('11:00:00', '11 AM'), ('12:00:00', '12 PM'), ('13:00:00', '01 PM'), ('14:00:00', '02 PM'), ('15:00:00', '03 PM'), ('16:00:00', '04 PM'), ('17:00:00', '05 PM'), ('18:00:00', '06 PM'), ('19:00:00', '07 PM'), ('20:00:00', '08 PM'), ('21:00:00', '09 PM'), ('22:00:00', '10 PM'), ('23:00:00', '11 PM')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='research',
            name='year',
            field=models.PositiveIntegerField(default=2018),
        ),
        migrations.AlterField(
            model_name='record',
            name='score',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('F', 'F')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
